version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]
  environment = [
    "browser",
    "jest",
    "nodejs"
  ]
  style_guide = "airbnb"

[[transformers]]
name = "standardjs"
enabled = true
